import mock from '../mock'

// ** Utils
import { paginateArray } from '../utils'
import { Book } from 'react-feather'

const data = [
  {
    responsive_id: '',
    id: 1,
    avatar: '10.jpg',
    full_name: "01234",
    description: '83010004 GMOAC',
    properties: <Book/>,
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'385',
    EAU:'343',
    onhand:'323',
    drawing_number: '206973',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 2
  },
  {
    responsive_id: '',
    id: 2,
    avatar: '1.jpg',
    full_name: "091234-001",
    description: 'Bonnet',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '091234',
    drawing_version: 'H',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 2
  },
  {
    responsive_id: '',
    id: 3,
    avatar: '9.jpg',
    full_name: "01234",
    description: 'Connector, GSKT & SCR',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '123434',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 5
  },
  {
    responsive_id: '',
    id: 4,
    avatar: '10.jpg',
    full_name: "0123448-001",
    description: 'Plungnut MMX',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '206973',
    drawing_version: 'K',
    item: 'OBSOLETE',
    i_owner:'AJN',
    status: 2
  },
  {
    responsive_id: '',
    id: 5,
    avatar: '',
    full_name: "FBX4567DGT78/DCD",
    description: 'SL SOL 15.3W',
    properties: 'onClick={handleModal}',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'121',
    EAU:'232',
    onhand:'222',
    drawing_number: '206660',
    drawing_version: '',
    item: 'ACT SEL',
    i_owner:'AFP',
    status: 2
  },
  {
    responsive_id: '',
    id: 6,
    avatar: '',
    full_name: "01234",
    description: '83010004 GMOAC',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '206973',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 1
  },
  {
    responsive_id: '',
    id: 7,
    avatar: '',
    full_name: "01234",
    description: '83010004 GMOAC',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '206973',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 3
  },
  {
    responsive_id: '',
    id: 8,
    full_name: "01234",
    description: '83010004 GMOAC',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '206973',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 3
  },
  {
    responsive_id: '',
    id: 9,
    full_name: "01234",
    description: '83010004 GMOAC',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '206973',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 2
  },
  {
    responsive_id: '',
    id: 11,
    avatar: '',
    full_name: "01234",
    description: '83010004 GMOAC',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '206973',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 4
  },
  {
    responsive_id: '',
    id: 12,
    avatar: '',
    full_name: "01234",
    description: '83010004 GMOAC',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '206973',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 4
  },
  {
    responsive_id: '',
    id: 13,
    avatar: '',
    full_name: "01234",
    description: '83010004 GMOAC',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '206973',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 4
  },
  {
    responsive_id: '',
    id: 14,
    avatar: '',
    full_name: "01234",
    description: '83010004 GMOAC',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '206973',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 2
  },
  {
    responsive_id: '',
    id: 15,
    avatar: '',
    full_name: "01234",
    description: '83010004 GMOAC',
    properties: '',
    drawingEU: '',
    drawingUS: '',
    product_structure: '',
    icsproduct_structure: '',
    whereused: '',
    impolde: '',
    AGR:'',
    EAU:'',
    onhand:'',
    drawing_number: '206973',
    drawing_version: 'G',
    item: 'OBSOLETE',
    i_owner:'AFP',
    status: 5
  }
]

mock.onGet('/api/datatables/initial-data').reply(() => {
  return [200, data]
})

mock.onGet('/api/datatables/data').reply(config => {
  // eslint-disable-next-line object-curly-newline
  const { q = '', perPage = 10, page = 1 } = config
  /* eslint-enable */

  const queryLowered = q.toLowerCase()
  const filteredData = data.filter(
    item =>
      /* eslint-disable operator-linebreak, implicit-arrow-linebreak */
      item.full_name.toLowerCase().includes(queryLowered) ||
      item.post.toLowerCase().includes(queryLowered) ||
      item.email.toLowerCase().includes(queryLowered) ||
      item.age.toLowerCase().includes(queryLowered) ||
      item.salary.toLowerCase().includes(queryLowered) ||
      item.start_date.toLowerCase().includes(queryLowered)
  )
  /* eslint-enable  */

  return [
    200,
    {
      allData: data,
      invoices: paginateArray(filteredData, perPage, page),
      total: filteredData.length
    }
  ]
})
